version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
  user-ms:
    build: ./user-ms
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - rabbitmq
  notification-ms:
    build:
      context: ./notification-ms
    depends_on:
      - rabbitmq
      - redis
